config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :flats  do
    resources :photos, only: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user

  has_many_attached :photos

  validates :address, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :flat_type, presence: true
  validates :guests, presence: true
  validates :bedrooms, presence: true
  validates :bathrooms, presence: true
  validates :flat_type, inclusion: { in: ["Entire place", "Private room", "Shared room"]}

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :flats, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
   after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)|(^index$)/
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def show
    @flat = Flat.geocoded.find(params[:id])
    @first_photo = @flat.photos.first
    @second_photo = @flat.photos[1]
    @third_photo = @flat.photos[2]
    @forth_photo = @flat.photos[3]
    @fifth_photo = @flat.photos[4]
    @markers = [{:lat=>@flat.latitude, :lng=>@flat.longitude}]
    authorize @flat
  end


  def index
     @flats = policy_scope(Flat.geocoded)
     @markers = @flats.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude
      }
    end
  end

  def new
    @flat = Flat.new
    authorize @flat
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    @flat.amenities.delete_at(0)
    authorize @flat
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
    authorize @flat
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.amenities.delete_at(0) if @flat.amenities[0] == ''
    authorize @flat
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:title, :address, :price, :guests, :bedrooms, :bathrooms, :flat_type, :description, amenities: [], photos: [])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def show
    @flat = Flat.find(params[:flat_id])
    @photos = @flat.photos
    authorize @flat
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flats/_index_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= cl_image_tag flat.photos.first.key, height: 400, width: 400, crop: :fill, class: 'd-block w-100' %>
    </div>
    <% flat.photos.drop(1).each do |photo| %>
        <div class="carousel-item">
         <%= cl_image_tag photo.key, height: 400, width: 400, crop: :fill, class: 'd-block w-100' %>
        </div>
      <% end %>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  </div>
</div>

app/views/flats/edit.html.erb
<div class="container">
  <h2>Let's update your space!</h2>

  <div>
    <%= simple_form_for @flat do |f| %>
      <%= f.input :flat_type, label: 'What kind of place do you have?', as: :select, collection: ["Entire place", "Private room", "Shared room"] %>
      <%= f.input :guests, label: 'How many guests can you accomodate?', as: :select, collection: 1..20 %>
      <%= f.input :address, label: 'Where is the listing?' %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :bedrooms, label: 'How many bedrooms are availabe for the guests?', as: :select, collection: 1..20 %>
      <%= f.input :bathrooms, label: 'How many bathrooms are available for the guests?', as: :select, collection: 1..20 %>
      <%= f.input :amenities, as: :check_boxes, collection: ["Essentials", "Wifi", "TV", "Heat", "Air conditioning", "Iron", "Shampoo", "Hair dryer", "Breakfast, coffee, tea", "Desk/workspace", "Fireplace", "Closet/drawers", "Private entrance"] %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/flats/index.html.erb
<div class="d-flex full-screen-container-index">
  <!-- flats -->
  <div class="left-container">
    <div class="search-results">
      <h2 class = "small-black-text">300+ stays  June 6-13  1 guest</h2>
      <h1 class = "bold-black-text">Stays in Tel Aviv-Yafo</h1>
      <h2>filter options</h2>
    </div>
    <div class="index-flat-cards">
      <% @flats.each do |flat| %>
        <div class="index-flat-card">
          <div class="flat-card-photos">
            <% if flat.photos.attached? %>
              <%= render 'index_carousel', flat: flat %>
            <% else %>
              <img src="https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
            <% end %>
          </div>
          <div class="index-card-details">
            <div>
              <h2 class = "small-light-grey-text"><%= flat.flat_type %></h2>
              <h2 class = "link"> <%= link_to flat.title, flat_path(flat), class: "flat-title-index", target: :_blank  %></h2>
              <h2 class = "small-light-grey-text"><%= flat.bedrooms %> bedrooms - <%= flat.bathrooms %> baths</h2>
              <h2 class = "small-light-grey-text"><%= flat.amenities %> bedrooms - <%= flat.bathrooms %> baths</h2>
            </div>
            <div class="index-flat-card-pricing">
              <div class = "flat-price"><strong>$<%= flat.price %></strong> / night</div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <!-- map -->
  <div class="right-container">
    <div id="map"
       style="width: 100%; height: 600px;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
     </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h2>Let's get started listing your space!</h2>

  <div>
    <%= simple_form_for @flat do |f| %>
      <%= f.input :flat_type, label: 'What kind of place do you have?', as: :select, collection: ["Entire place", "Private room", "Shared room"] %>
      <%= f.input :guests, label: 'How many guests can you accomodate?', as: :select, collection: 1..20 %>
      <%= f.input :address, label: 'Where is the listing?' %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :bedrooms, label: 'How many bedrooms are availabe for the guests?', as: :select, collection: 1..20 %>
      <%= f.input :bathrooms, label: 'How many bathrooms are available for the guests?', as: :select, collection: 1..20 %>
      <%= f.input :amenities, as: :check_boxes, collection: ["Essentials", "Wifi", "TV", "Heat", "Air conditioning", "Iron", "Shampoo", "Hair dryer", "Breakfast, coffee, tea", "Desk/workspace", "Fireplace", "Closet/drawers", "Private entrance"] %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container">
  <div class="container">
    <h1><%= @flat.title %> </h1>
    <p> <u> <%= @flat.address %></p></u>
    <div class="flat_carousel">
      <div class="big-photo">
              <% if @first_photo %>
                <%= cl_image_tag @first_photo.key, height: 400, width: 400, crop: :fill, class: 'd-block w-100 show-card-img' %>
              <% else %>
                <img src="https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
              <% end %>
            </div>
            <div class="second_photos_div">
              <% if @second_photo %>
                <%= cl_image_tag @second_photo.key, height: 400, width: 400, crop: :fill, class: 'd-block w-100 show-card-img' %>
              <% else %>
                <img src="https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
              <% end %>
              <% if @third_photo %>
                <%= cl_image_tag @third_photo.key, height: 400, width: 400, crop: :fill, class: 'd-block w-100 show-card-img' %>
              <% else %>
                <img src="https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
              <% end %>
            </div>
            <div class="third_photos_div">
                <% if @forth_photo %>
                  <%= cl_image_tag @forth_photo.key, height: 400, width: 400, crop: :fill, class: 'd-block w-100 show-card-img' %>
                <% else %>
                  <img src="https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
                  <% end %>
                <% if @fifth_photo %>
                  <%= cl_image_tag @fifth_photo.key, height: 400, width: 400, crop: :fill, class: 'd-block w-100 show-card-img' %>
                <% else %>
                  <img src="https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
                <% end %>
              <div class="btn-flex">
                <%= link_to "Show all photos",  flat_photo_path(@flat), class: "btn-flex" %>
              </div>
          </div>
      </div>
    </div>
    <div class="card-flat">
      <div class="card-flat-infos">
        <div>
          <h2><%= @flat.flat_type.capitalize %> hosted by <%=  @flat.user.email%></h2>
          <div class="card-flat-info-flex">
            <% if @flat.guests == 1 %>
              <p><%= @flat.guests %> guest· </p>
            <%else %>
              <p><%= @flat.guests %> guests· </p>
            <%end %>

            <% if @flat.bedrooms == 1 %>
              <p><%= @flat.bedrooms %> bed· </p>
            <%else %>
              <p><%= @flat.bedrooms %> beds· </p>
            <%end %>

            <% if @flat.bathrooms == 1 %>
              <p><%= @flat.bathrooms %> bath </p>
            <%else %>
              <p><%= @flat.bathrooms %> baths </p>
            <%end %>
          </div>
        </div>
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      </div>
    </div>
    <hr>

    <div class="details">
      <div class="details-flex">
        <svg viewBox="0 0 1000 1000" role="presentation" aria-hidden="true" focusable="false" style="height: 24px; width: 24px; display: block; fill: currentcolor;"><path d="M928 417L680 606l95 306c3 12-6 24-16 24-3 0-5-1-8-4L500 741 251 931c-8 5-18 3-23-4-4-5-4-7-3-12l1-1 94-306L72 417c-8-7-10-11-6-23 3-8 9-12 14-12h309l96-307c2-6 8-11 14-11 7 0 13 5 16 13l96 305h309c6 0 12 4 14 12 4 12 3 16-6 23m44-35c-8-24-29-40-52-40H640L553 65c-7-24-29-41-54-41-24 0-45 16-52 39l-87 279H80c-23 0-44 16-52 40-9 28-2 50 19 67l227 174-86 278c-7 18-4 35 8 51 19 24 53 29 78 12l226-172 226 172c10 8 21 12 33 12 36 0 65-36 54-75l-87-280 226-172c22-17 29-39 20-67"></path></svg>
        <h4><%= @flat.flat_type.capitalize %></h4>
      </div>
      <% if @flat.flat_type == "entire place" %>
        <p>You'll have the apartment to yourself</p>
      <%elsif @flat.flat_type == "private room"%>
        <p>You'll have the room to yourself</p>
      <%else %>
        <p>You'll have the share the apartment with wonderful people</p>
      <%end %>
    </div>
    <hr>

    <div class="description">
      <p class="description-ph">
        <%= @flat.description.first(500) %><span id="dots">…</span><span id="more">
         <%= @flat.description[500..-1] %> </span>.</p>
        <button onclick="myFunction()" id="myBtn">Read more</button>
    </div>
      <h class=> Contant host</h3>
    <hr>

    <div class="amenities">
      <h3>Aminities</h3>
      <ul>
      <% @flat.amenities.each do |amenity| %>
        <li><%= amenity %></li>
      <% end %>
      </ul>
    </div>
    <hr>

    <div class="dates">
      <h3>Selet check-in date</h3>
      <h4>Add your travel dates for exact pricing</h4>
    </div>
    <hr>

    <div class="reviews">
      <div class="ave-reviews">
        4.73 (233 reviews)
      </div>
    </div>
    <hr>

      <h3>Location</h3>
       <div class="location">
        <div id="map"
         style="width: 100%; height: 600px;"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
       </div>
      </div>
    <hr>

    <div class="host-card">
      <div class="host">
        <div class="host-img">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        </div>
        <div class="host-details">
          <h2>Hosted by <%= @flat.user.email %></h2>
          <p>Joined in <%= @flat.user.created_at.strftime("%B %Y") %> </p>
        </div>
      </div>
        <h3>During your stay</h3>
      </div>
    <hr>

    <div class="flat-details">
      <h2>Things to know</h2>
      <div class="flat-details-flex">
        <div class="flat-details-house-roules">
          <p>House rules</p>
          <p>Addtional rules</p>
        </div>
        <div class="flat-details-cancellation">
          <p>Cancellation policy</p>
        </div>
    </div>
  </div>
</div>

<script>
  function myFunction() {
  var dots = document.getElementById("dots");
  var more = document.getElementById("more");
  var btn = document.getElementById("myBtn");
// dots is not showing
  if (dots.style.display === "none") {
    dots.style.display = "inline";
    btn.innerHTML = "Read more";
    // dont show the moretext div text.
    more.style.display = "none";
  } else {
    //dont show the dots
    dots.style.display = "none";
    // change the inner text to read less
    btn.innerHTML = "Read less";
    // the rest display inline.
    more.style.display = "inline";
  }
}

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirBnb20</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700;900&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/photos/show.html.erb
<%= link_to 'X Close', flat_path(@flat), class: "photos_btn" %>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li class="not-visible-sx" data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li class="not-visible-dx"  data-target="#myCarousel" data-slide-to=@photos[-1]></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= cl_image_tag @photos.first.key, height: 400, width: 400, crop: :fill, class: 'd-block w-100' %>
    </div>
    <% @photos.drop(1).each do |photo| %>
        <div class="carousel-item">
         <%= cl_image_tag photo.key, height: 400, width: 400, crop: :fill, class: 'd-block w-100' %>
        </div>
      <% end %>
  <a class="carousel-control-prev " href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next " href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>